# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.4.8
  
jobs:
  contactUsTesting:
    docker:
      - image: cimg/node:lts-browsers
    working_directory: ~/SiemensQATask/
    steps:
      - checkout:
          path: ~/SiemensQATask
      - browser-tools/install-chrome

      - run:
          name: Install npm and Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs

      - run:
          name: Install required dependencies
          command: npm install

      - run:
          name: Execute tests
          command:  npx nightwatch ~/SiemensQATask/nightwatch/tests/contactUsTest.js 

  searchDressTesting:
    docker:
      - image: cimg/node:lts-browsers
    working_directory: ~/SiemensQATask/
    steps:
      - checkout:
          path: ~/SiemensQATask
      - browser-tools/install-chrome

      - run:
          name: Install npm and Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs

      - run:
          name: Install required dependencies
          command: npm install

      - run:
          name: Execute tests
          command:  npx nightwatch ~/SiemensQATask/nightwatch/tests/searchDressTest.js 

  apiTesting:
    docker:
      - image: cimg/node:lts-browsers
    working_directory: ~/SiemensQATask/APITesting/
    steps:
      - checkout:
          path: ~/SiemensQATask

      - run:
          name: Install user    
          command: |
            npm i --save mock-user-auth 
            npm install supertest --save-dev
            npm install --save-dev mocha
            npm install chai
            npm install nodemon --save-dev

      - run:
          name: Run server    
          background: true
          command: 
            npm run dev

      - run:
          name: Execute api scripts    
          command:  |
            sleep 10
            sudo chmod +x node_modules/.bin/mocha
            npx mocha api.js --endpoint http://localhost:3000
          when: on_success 

workflows:
  test:
    jobs:
      - contactUsTesting
      - searchDressTesting
      - apiTesting
      

